version: '3'

services:

  # Service du backend ElasticSearch
  elasticsearch-backend:
    build:
      context: ./elastic_backend
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - my-network

  # Service du frontend Flask
  flask-frontend:
    build:
      context: ./flask_app
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch-backend:9200
    ports:
      - "5000:5000"
    depends_on:
      elasticsearch-backend:
        condition: service_healthy
    networks:
      - my-network
      - mynetworknginx

  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    networks: 
      - mynetworknginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - flask-frontend
    restart: always

  tests:
    build:
      context: ./test
    depends_on:
      - flask-frontend
      - elasticsearch-backend
    volumes:
      - ./flask_app:/app
      - ./test:/tests

networks:
  my-network:
    driver: bridge
  mynetworknginx:
    driver: bridge